version: '3'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: postgres
      volumes:
        - "C:/Users/sagar/data/psql:/var/lib/postgresql/data"
      environment:
        POSTGRES_DB: simpledb
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      ports:
        - 5432:5432